spring:
  application:
    name:
      Woroutine
  profiles:
    include:
      - db
      - key

  # jpa hibernate
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true
  main:
    allow-bean-definition-overriding: true